### ISSUE TITLE
Distribute hp.owl in a more reliable way

### ISSUE THREAD

**Issue by cmungall** [obophenotype/upheno#194] opened 2016-09-09 21:56 UTC
Currently http://purl.obolibrary.org/obo/hp.owl redirects to jenkins. Jenkins isn't really intended as a fileserver. Import chains with hp.owl frequently fail

Some other options:
1. Serve out of a github raw URL. See for example [PATO](https://github.com/pato-ontology/pato/blob/master/src/ontology/README-editors.md)
2. Have jenkins push to a S3/cloundfront
3. Use the central OBO build and distribution mechanism - see [OBO build docs](http://obofoundry.org/faq/what-is-the-build-field.html)
4. Build failover/cacheing upstream, and use catalog-xml

What do you think @drseb?

Our jenkins is already set up for the S3 push, if we want to go 2

**Comment by cmungall** [comment] 2016-09-09 21:57
one particular problem noted is that rather than simply timing out, jenkins delivers an HTML file with an error message instead of RDF/XML, resulting in:

```
--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '<?xml version="1.0"?>' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)

--------------------------------------------------------------------------------
```

**Comment by drseb** [comment] 2016-09-25 09:42
> Our jenkins is already set up for the S3 push, if we want to go 2

but your jenkins uses a problematic version of oort that produces a problematic hp.obo. any other ideas?

**Comment by drseb** [comment] 2016-09-25 11:26
switching to gh release would be ok, but I still would like to have a way to add the old releases.

**Comment by cmungall** [comment] 2016-09-26 17:27
On 25 Sep 2016, at 2:42, Sebastian Köhler wrote:

>> Our jenkins is already set up for the S3 push, if we want to go 2
> but your jenkins uses a problematic version of oort that produces a 
> problematic hp.obo. any other ideas?

The job can be configured to use any version of oort we like (although 
it's easiest if it's the latest and not a historic version). It's 
easiest if it just executes a target in the makefile that is in the 
repo.

Not sure what you mean by a problematic version, but oort is deprecated 
in any case.

**Comment by drseb** [comment] 2017-01-12 14:04
Duplicate of https://github.com/obophenotype/human-phenotype-ontology/issues/1155

**Closed by drseb** 2017-01-12 14:04 UTC
